<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<title>RTR Prototype</title>
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/colorbox.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/read.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/edit.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/jquery.ui.theme.css" media="screen" />
	
	<script src="js/jquery.min.js" type="text/javascript"></script>
	<script src="js/jquery.colorbox.js" type="text/javascript"></script>
	<script src="js/jquery.blockui.js" type="text/javascript"></script>
	<script src="js/jquery.wrapSelection.js" type="text/javascript"></script>
	<script src="js/jquery.expander.js" type="text/javascript"></script>
	<script src="js/jquery.string.js" type="text/javascript"></script>
	<script src="js/jquery-ui-draggable.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/jQuery.jPlayer.2.1.0/jquery.jplayer.min.js"></script>
	<script type="text/javascript" src="js/jquery.narrateify.js"></script>
	<script src="js/jquery.print.js" type="text/javascript"></script>
	<script src="js/rtr.js" type="text/javascript"></script>
	
	<link href='http://fonts.googleapis.com/css?family=Didact+Gothic&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css' />
	
</head>
<body>